# Page settings
baseurl = "localhost:1313"
title = "TechGarage"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "TechGarage"
    home = "Home"
    services = "Courses"
    work = "We Teach"
    testimonials = "Why Tech"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
#    title = "Nurturting the Makers of Tomorrow."
#    subtitle = 'Another free HTML5 bootstrap template by <a href="http://freehtml5.co/" target="_blank" title="Free HTML5 Bootstrap Templates">FREEHTML5.co</a> released under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank">Creative Commons 3.0</a><br> ported for Hugo by <a href="http://saey55.gitlab.io/pietercv" target="_blank">Pieter Saey</a>'
     title = "Nurturing the Creators of Tomorrow."
     subtitle = 'Learn to Code, Build Robots, Build your own Laptop, Build Mobile Apps, Build AI power Apps, Talk to Robots'
     
#We use the most amazing tools and technoglogies avaiable in the world which are specially built for kids 

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?time_continue=1&v=6XvmhE1J9PY"


  # Services section
  [params.services]
    enable = true
    title = "Courses"
    description = "We have curated the best courses in the world to teach topics ranging various skills which we consider the most important ones for the creators of tomorrow. "

    [[params.services.item]]
      title = "Coding"
      description = "According to the U.S. Bureau of Labor Statistics, software developer jobs are expected to grow 17% from 2014 till 2024. They categorize this growth as 'much faster' than the average rate among other professions"
      icon = "icon-laptop"

    [[params.services.item]]
      title = "Robotics"
      description = "The world is going to see more and more robots in every field and the demand for engineers who can build better robots will only grow. These courses will teach the kids to be prepared for the future world of robots."
      icon = "icon-bitbucket"
      
    [[params.services.item]]
      title = "Game Development"
      description = "Video Games Industry Revenue is expected to hit $180 billion in 2018. Opportunity size is growing bigger and bigger. Creating games makes kids more creative and also helps them grow their logical thinking."
      icon = "icon-gamepad"

      [[params.services.item]]
      title = "Design"
      description = "Every man made object is designed and created by someone. The process of designing and seeing it coming to life is one of the best learning methodology since ancient times. But today our education systems have forgotten that."      
      icon = "icon-monitor"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Why Tech Skills are the most Important skills of 21st Century?"
    description = "Technological advancements in the last 10 years have changed every thing in our lives. This is only going to get better going forward. Technological skills will be as important and basic as knowing how to read and write. <b>Irrespective of the jobs today's kids are going to be doing in the future, Computer skills will play a very big role in their growth and success.</b>"

    [[params.testimonials.item]]
      quote = "&ldquo;Everybody in this country should know how to learn to program a computer.. because it teaches you how to think.&rdquo;"
      person = 'Steve Jobs<span class="subtext">Apple Founder</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Learning to write programs stretches your mind, and helps you think better, creates a way of thinking about things that I think is helpful in all domains.&rdquo;"
      person = 'Bill Gates <span class="subtext">Co-Founder, Microsoft</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Computers are going to be a big part of our future...and that future is yours to shape. &rdquo;"
      person = 'Barack Obama <span class="subtext">Former President</span>'
      img = "person3.jpg"
      alt = "Person3"
    
  # About section
  [params.about]
    enable = true
    title = "About TechGarage"
#    description = "We are a team of IT Engineers having more than 2 decades of combined IT experience who believe that we in India have not been using the worlds best tools and technologies for teaching kids the most important skill of the 21ST CENTURY "
#    description = "<b>We are a team of IT Engineers having more than 2 decades of combined IT experience.</b> We believe every kid in this country should be equipped with the skills required to be <b>'Creator of Tomorrow'</b>. We cant just let our kids be the consumers of the tools and technologies created by others. This is our small effort in making our country Tech Skills Capital of the World."
     description = "<b> TechGarage is a initiative by a Team of IT Engineers having more than 2 decades of combined IT experience.</b> Through TechGarage we want to teach kids the most important skills of the 21st Century in the most fun loving way possible. We will be using the world's best tools and technologies."
    
    
    [[params.about.item]]
      name = "Tech Garage"
      position = ""
      description = ""
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Tech Garage"
      position = ""
      description = ""
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Tech Garagee"
      position = ""
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "For more information on the Courses"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Silicon Valley of India, Bengaluru, India"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@techgarage.com"],
        ["icon-globe", '<a href="https://techgarage.com/" target="_blank">techgarage.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
